package com.ltd_tech.readsdk;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ltd_tech.readsdk.entities.BookEntity;
import com.ltd_tech.readsdk.entities.ReadTable;

import com.ltd_tech.readsdk.BookEntityDao;
import com.ltd_tech.readsdk.ReadTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookEntityDaoConfig;
    private final DaoConfig readTableDaoConfig;

    private final BookEntityDao bookEntityDao;
    private final ReadTableDao readTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookEntityDaoConfig = daoConfigMap.get(BookEntityDao.class).clone();
        bookEntityDaoConfig.initIdentityScope(type);

        readTableDaoConfig = daoConfigMap.get(ReadTableDao.class).clone();
        readTableDaoConfig.initIdentityScope(type);

        bookEntityDao = new BookEntityDao(bookEntityDaoConfig, this);
        readTableDao = new ReadTableDao(readTableDaoConfig, this);

        registerDao(BookEntity.class, bookEntityDao);
        registerDao(ReadTable.class, readTableDao);
    }
    
    public void clear() {
        bookEntityDaoConfig.clearIdentityScope();
        readTableDaoConfig.clearIdentityScope();
    }

    public BookEntityDao getBookEntityDao() {
        return bookEntityDao;
    }

    public ReadTableDao getReadTableDao() {
        return readTableDao;
    }

}
