package com.ltd_tech.readsdk.entities.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ltd_tech.readsdk.entities.BookChapterTable;
import com.ltd_tech.readsdk.entities.BookEntity;
import com.ltd_tech.readsdk.entities.CollectionTable;
import com.ltd_tech.readsdk.entities.ReadTable;

import com.ltd_tech.readsdk.entities.dao.BookChapterTableDao;
import com.ltd_tech.readsdk.entities.dao.BookEntityDao;
import com.ltd_tech.readsdk.entities.dao.CollectionTableDao;
import com.ltd_tech.readsdk.entities.dao.ReadTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookChapterTableDaoConfig;
    private final DaoConfig bookEntityDaoConfig;
    private final DaoConfig collectionTableDaoConfig;
    private final DaoConfig readTableDaoConfig;

    private final BookChapterTableDao bookChapterTableDao;
    private final BookEntityDao bookEntityDao;
    private final CollectionTableDao collectionTableDao;
    private final ReadTableDao readTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookChapterTableDaoConfig = daoConfigMap.get(BookChapterTableDao.class).clone();
        bookChapterTableDaoConfig.initIdentityScope(type);

        bookEntityDaoConfig = daoConfigMap.get(BookEntityDao.class).clone();
        bookEntityDaoConfig.initIdentityScope(type);

        collectionTableDaoConfig = daoConfigMap.get(CollectionTableDao.class).clone();
        collectionTableDaoConfig.initIdentityScope(type);

        readTableDaoConfig = daoConfigMap.get(ReadTableDao.class).clone();
        readTableDaoConfig.initIdentityScope(type);

        bookChapterTableDao = new BookChapterTableDao(bookChapterTableDaoConfig, this);
        bookEntityDao = new BookEntityDao(bookEntityDaoConfig, this);
        collectionTableDao = new CollectionTableDao(collectionTableDaoConfig, this);
        readTableDao = new ReadTableDao(readTableDaoConfig, this);

        registerDao(BookChapterTable.class, bookChapterTableDao);
        registerDao(BookEntity.class, bookEntityDao);
        registerDao(CollectionTable.class, collectionTableDao);
        registerDao(ReadTable.class, readTableDao);
    }
    
    public void clear() {
        bookChapterTableDaoConfig.clearIdentityScope();
        bookEntityDaoConfig.clearIdentityScope();
        collectionTableDaoConfig.clearIdentityScope();
        readTableDaoConfig.clearIdentityScope();
    }

    public BookChapterTableDao getBookChapterTableDao() {
        return bookChapterTableDao;
    }

    public BookEntityDao getBookEntityDao() {
        return bookEntityDao;
    }

    public CollectionTableDao getCollectionTableDao() {
        return collectionTableDao;
    }

    public ReadTableDao getReadTableDao() {
        return readTableDao;
    }

}
